export const VISITOR_STATUS = {
  PENDING_GUARD: 'PENDING_GUARD',
  SENT_FOR_APPROVAL: 'SENT_FOR_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  GATE_IN: 'GATE_IN',
  MEET_IN: 'MEET_IN',
  MEET_OUT: 'MEET_OUT',
  GATE_OUT: 'GATE_OUT',
  CANCEL_MEET: 'CANCEL_MEET',
  DENIED_BLACKLIST: 'DENIED_BLACKLIST',
};

export const STATUS_LABELS: Record<string, string> = {
  PENDING_GUARD: 'PENDING GUARD',
  SENT_FOR_APPROVAL: 'FORWARDED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  GATE_IN: 'GATE IN',
  MEET_IN: 'MEET IN',
  MEET_OUT: 'MEET OUT',
  GATE_OUT: 'GATE OUT',
  CANCEL_MEET: 'CANCEL MEET',
  DENIED_BLACKLIST: 'DENIED BLACKLIST',
  COMPLETED: 'GATE OUT',
  IN_MEETING: 'MEET IN',
  CHECKED_IN: 'GATE IN',
  CHECKED_OUT: 'GATE OUT',
  ACTIVE: 'ON-SITE'
};

export const STATUS_GROUPS = {
  PENDING: [VISITOR_STATUS.SENT_FOR_APPROVAL],
  ACTIVE: [VISITOR_STATUS.APPROVED, VISITOR_STATUS.GATE_IN, VISITOR_STATUS.MEET_IN, VISITOR_STATUS.MEET_OUT],
  HISTORY: [VISITOR_STATUS.REJECTED, VISITOR_STATUS.GATE_OUT, VISITOR_STATUS.CANCEL_MEET, VISITOR_STATUS.DENIED_BLACKLIST],
};
